// Class automatically generated by Dev-C++ New Class wizard

#ifndef ESTUDIANTE_H
#define ESTUDIANTE_H
#include <string.h>

class Estudiante

{
      private:
      int cedula;
      char  *Correo,*Nombre ;
	public:
   
		Estudiante();
        ~Estudiante();
        void setNombre(char *);
		void setCorreo(char *);
		void setCedula(int);
		int getCedula();
		char* getNombre();
		char* getCorreo();
};

#endif
